#+TITLE: Guilherme Guerra
#+STARTUP: indent

Trabalho com tecnologias open source desde 2007. Me sinto motivado
pelo conceito de compartilhamento de código e conhecimento. Acredito
que absorver diversos pontos de vista permite melhorar
significativamente o trabalho, por isso me sinto melhor em ambientes
multidisciplinares. Acreditar e perseguir essas práticas me
possibilitou trabalhar em diversos setores da economia. Hoje como
desenvolvedor Front-end com foco em interface busco novos desafios que
me permitam contribuir não somente com as minhas skills técnicas mas
com as experiências e pontos de vista que venho trocando e absorvendo.

* Formação
** Pedagogia - UFRGS ( Incompleto )
** Ciência da Computação - Fumec ( Incompleto )
** Técnico em informática Gerencial pele Colégio e Faculdade COTEMIG

* Experiência Profissional
** [[http://www.objectedge.com/][Object Edge]] (Desde Out/2015) (Porto Alegre)
*HTML*, *CSS*, *JavaScript*, *React*, *Relay*, *GraphQL*

** [[http://rentalocalfriend.com][Rent a Local Friend]] (Jul/2014 - Set/2015) (Rio de Janeiro)
*HTML*, *Sass*, *JavaScript*, *Ruby*, *Rails*

Desenvolvedor Fullstack e minha primeira experiência com startup

** [[http://ouishare.net/en][OuiShare]] (Engage) - (Porto Alegre / Europa) - [[http://github.com/OuiShare/OuiShare][Código Fonte]]
*HTML*, *Sass*, *JavaScript*, *Ruby*, *Rails*

#+BEGIN_QUOTE
Foi um único projeto, mas que me abriu portas e me preparou para
trabalhar na Rent a Local Friend. Minha primeira experiência com Ruby
on Rails e a oportunidade de trabalhar com uma equipe espalhada pelo
globo.
#+END_QUOTE

** [[https://github.com/gabinetedigital/][Gabinete Digital]] (2011 - 2013) (Porto Alegre)
*HTML*, *Sass*, *JavaScript*, *Python*, *Flask*

#+BEGIN_QUOTE
Fui responsável por toda a parte visual, desde o layout do site e das
ferramentas até os banners de divulgação e apresentações. Contribui na
definição das tecnologias e ferramentas utilizadas tanto em front end
quanto back end, além de implementar toda a parte front end. Quando
necessário contribuia com o back-end.
#+END_QUOTE

** [[http://memelab.com.br/][memeLab]] (2011 - 2012) (São Paulo)
*HTML*, *Sass*, *JavaScript*, *Python*, *Django*

#+BEGIN_QUOTE
Foram poucos meses de trabalho remoto na memeLab, mas de muito
aprendizado. Fui responsável pela manutenção e correção de bugs de
alguns projetos que eles desenvolveram, além de instalação e manutenção
de servidores.

Essa parceria resultou em novo projeto realizado em 2012 chamado
[[http://memelab.com.br/projeto/incubadora][Incubadora - Versão final]], que é um Teatro Game onde as pessoas
interagem com o espetáculo através dos seus dispositivos móveis. Fui
responsável pelo desenvolvimento front end das interfaces mobile e
desktop.
#+END_QUOTE

[[https://github.com/guilhermecomum/incubadora/][Código Fonte]]

**  Megaware Industrial Ltda (2008 - 2011) - (Belo Horizonte)

#+BEGIN_QUOTE
Após quatro anos trabalhando em estruturas do governo, eu queria
conhecer a iniciativa privada. Assim fui trabalhar na fábrica. Tudo
que havia aprendido com o uso e o trabalho com softwares livres eu
pude aplicar no desenvolvimento e customização do Megalinux,
distribuição (baseada no Ubuntu).

O CCL - Controle Computacional da Linha era o sistema responsável por
todo o processo da montagem dos computadores, dividido em três partes:
MegaInteg (FreeDos), MegaClone (Linux) e Megacontrol (Django). Meu
trabalho consistia na manutenção dessas aplicações, adicionando novos
drivers, monitorando os servidores além de fazer pequenos patches para
o Megacontrol.
#+END_QUOTE

** Centro Cultura da UFMG / CCNM (2004 – 2008) - ( Belo Horizonte )
#+BEGIN_QUOTE
Projeto de Inclusão e Letramento Digital Rede.lê/UFMG /
Centro de Convergência de Novas Mídias da UFMG (Grupo de Pesquisa / Pontão de Cultura)

Foi onde tudo começou, meu primeiro estágio. Tive contato direto com
desenvolvimento de sites e software livre. Era responsável por
encontrar soluções livres para as necessidades do projeto e treinar as
pessoas para utilizá-los.

[[http://www.institutoembratel.org.br/cursos/curso_ccnm/][Curso Online - CCNM]]

Quando a rede.lê virou um projeto dentro do CCNM, eu virei um dos coordenadores. Participei
coordenação e elaboração, do design e da implementação das ferramentas, metodologias e sites.
#+END_QUOTE

* Atividades complementares
** [[https://www.taturanamobi.com.br/][Taturana]] - [[https://github.com/nucleo-digital/plataforma-taturana][Código Fonte]] (Front-end/Freelancer)
** Monitor da disciplina de Educação especial e inclusão - UFRGS
** [[http://transportador.net/][Transportador.net]] (Front-end/Freelancer)
** [[http://www.impulsoti.com.br/][Impulso TI]] (Front-end/Freelancer)
** Identidade visual FISL 15 (Designer/Freelancer)- [[https://github.com/guilhermecomum/fisl15][Código Fonte]]

* Eventos
** FISL 15/Latinoware (2014) – Palestra Espaços abertos colaborativos
** FISL 14 (2013) – Palestra Front-end sem dor ( ou quase isso )
** FISL 14 (2013) – Oficina de Videomapping
** FISL 14 (2013) – Palestra Incubadora – Interação no teatro mediada por Software Livre
